services:


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: empform_backend
    labels:
      autodeploy.owner_id: "6a88317adfbae6f2689bac47"
      autodeploy.project_id: "6ac8d118ec9a1c8930b8f042"
      autodeploy.job_id: "6ac8d0e6ec9a1c8930b8f03e"
      autodeploy.managed: "true"
      autodeploy.service: "backend"
    restart: unless-stopped
    ports:
      - "2000:2000"
    env_file:
      - ./.env