services:


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: form_backend
    labels:
      autodeploy.owner_id: "6a88317adfbae6f2689bac47"
      autodeploy.project_id: "6ac87fcb00c5d2663a15f8db"
      autodeploy.job_id: "6ac87f8600c5d2663a15f8d7"
      autodeploy.managed: "true"
      autodeploy.service: "backend"
    restart: unless-stopped
    ports:
      - "2000:2000"
    env_file:
      - ./backend/.env